name: Mi Workflow Padre

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Hola desde el paso 1"
      - name: Invocar Workflow Hijo
        uses: peter-evans/workflow-dispatch@v2
        with:
          workflow: Workflow-Hijo
          token: ${{ secrets.GITHUB_TOKEN }}
          # Puedes añadir inputs si el flujo de trabajo hijo los necesit
