name: Mi Workflow Padre

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      workflow-name:
        description: 'Nombre dDDld workflow a invocar'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Hola desde el paso 1"
      - name: Invocar Workflow Hijo
        uses: actions/checkout@v2
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}  # Asegúrate de tener un PAT con los permisos necesarios
          repository: ${{ github.repository_owner }}/Workflow-Hijo
          event-type: workflow_dispatch
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

