name: Mi Workflow Padre

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      workflow-name:
        description: 'Nombre del workflow a invocar'
        required: true
      job-id:
        description: 'ID del job a ejecutar en el workflow hijo'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      BANCO: 'BCP'
      PAIS: 'bolivia'
    steps:
      - name: Paso 1
        run: echo "Hola desde el paso 1"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1 en Workflow Hijo
        run: |
          echo "Hola desde el paso 1 en Workflow Hijo"
          echo "BANCO: ${{ needs.job1.outputs.BANCO }}"
          echo "PAIS: ${{ needs.job1.outputs.PAIS }}"

      - name: Invocar Workflow Hijo
        uses: actions/checkout@v2
        with:
          repository: "${{ github.repository_owner }}/first-gh"
          token: "${{ secrets.PAT }}"
          ref: main
          path: child-repo

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: "${{ secrets.PAT }}"
          repository: "${{ github.repository_owner }}/first-gh"
          event-type: workflow_dispatch
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "job-id": "job2" }'
