name: Mi Workflow Padre

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Hola desde el paso 1"
      - name: Invocar Workflow Hijo
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/:owner/:repo/dispatches \
            -d '{"event_type": "trigger-workflow-hijo"}'
