name: Mi Workflow Padre

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Hola desde el paso 1"
      - name: Invocar Workflow Hijo
        uses: peter-evans/repository-dispatch@v2  # Check the correct version
        with:
          workflow: Workflow-Hijo
          token: ${{ secrets.GITHUB_TOKEN }}
