name: Workflow Hijo

on:
  repository_dispatch:

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1 en Workflow Hijo
        run: |
          echo "Hola desde el paso 1 en Workflow Hijo"
          echo "BANCO: $BANCO"
          echo "PAIS: $PAIS"
