name: Workflow Hijo

on:
  repository_dispatch:

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1 en Workflow Hijo
        run: |
          echo "ESTE ES EL WORKFLOW DE GIT HUB HIJO"
          echo "BANCO: ${{ github.event.inputs.banco }}"
          echo "PAIS: ${{ github.event.inputs.pais }}"
